name: Update README on First Push

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if first run flag exists
        id: check-flag
        run: |
          if [ -f "SET_UP_NOTES.md" ]; then
            echo "First run already completed. Exiting."
            exit 0
          else
            echo "First run flag not found. Proceeding."
          fi

      - name: Get repository name
        id: vars
        run: echo "::set-output name=repo::${GITHUB_REPOSITORY}"

      - name: Replace placeholder with repo URL
        run: |
          repo_url=${{ steps.vars.outputs.repo }}
          sed -i "s|{{repo_url}}|${repo_url}|g" README.md
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with repository URL"
          git push

      - name: Create first run flag
        run: |
          touch SET_UP_NOTES.md
          echo "Things to do:\n-replace <skill> with name of track/n-fill in requirements\n-add summary to top of README.md\n-add picture of badge to bottom of README (uncomment existing code and add to <img src= />)" > SET_UP_NOTES.md
          git add SET_UP_NOTES.md
          git commit -m "Add first run completion flag (SET_UP_NOTES.md)"
          git push
